language: java

#jdk: 
#   - openjdk8
#   - openjdk9

matrix:
   include:
      - jdk: openjdk8
      - jdk: openjdk9
      - os: osx
        osx_image: xcode10.1

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
    - mvn -f ciExamples.myproject/pom.xml clean verify