language: java

#jdk: 
#   - openjdk8
#   - openjdk9

matrix:
   include:
      # always build this environment
      - jdk: openjdk8
      # only on pull request
      - jdk: openjdk9
        if: type IN (pull_request)
      # only on pull request
      - os: osx
        osx_image: xcode10.1
        if: type IN (pull_request)
        
# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
    - mvn -f ciExamples.myproject/pom.xml clean verify